language: ruby
script: bundle exec rake test
before_install: gem install bundler
os:
  - linux
  - osx
rvm:
  - "1.9.3"
  - "1.8.7"
  - "2.0.0"
  - "2.1.10"
  - "2.2.4"
  - "ruby-head"
  - "rbx"
  - "system"
env:
  - CC=gcc
  - CC=clang
matrix:
  allow_failures:
    - rvm: system
    - os: osx
      rvm: "2.2.4"
    - os: osx
      rvm: ruby-head
    - rvm: "rbx"
    - rvm: "rbx-head"
    - rvm: "1.8.7"
    - rvm: "1.9.3"
